name: feat workflow
on:
  push:
    branches: [develop]
    types: [open, reopened]
jobs:
  build-feature:
    # Maquina virtual runner
    runs-on: ubuntu-latest
    steps:
      # Descarga el codigo del repositorio
      - uses: actions/checkout@v5
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: pull and checkout from git repository
      # Solo imprime el texto
        run: |
          echo "Se hizo pull y checkout en el repositorio"
      # Descarga la maquina virtual de java
      - name: setup java 17
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17' # version de java para version 17
      - name: Cache maven dependecies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository # configuracion del cache
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: build maven and clean
        run: |
          mvn clean test package
          echo "build with maven"