name: feat workflow
on:
  push:
    branches:
      - feature/*
jobs:
  build-feature:
    # Maquina virtual runner
    runs-on: ubuntu-latest
    steps:
      # Descarga el codigo del repositorio
      - uses: actions/checkout@v5
      - name: pull and checkout from git repository
      # Solo imprime el texto
        run: |
          echo "Se hizo pull y checkout en el repositorio"
      # Descarga la maquina virtual de java
      - uses: actions/setup-java@v5
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17' # version de java
      - run: |
          mvnw clean install
          echo "build with maven"